# These are supported funding model platforms

github: jeyso215
open_collective: 
ko_fi: Jeyso
liberapay: Jeyso
custom: 45K3QyhGGysAGDvFhGnYne3qcajeGmjRXXGZ8p3LeWBxFgiDkZ7XhLuNxDB5QsjS8ySQtHmjGaoWc6Vg5wtfaPmoCHRDmC4 
