version: "3.6"

services:
  simplytranslate:
    container_name: simplytranslate
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./sockets:/go/web/sockets
    environment:
      - LISTEN_UNIX=true
      - GOOGLETRANSLATE_ENABLE=true
      - ICIBA_ENABLE=true
      - REVERSO_ENABLE=true
    
