FROM alpine/git:latest AS gitimport
RUN git clone -b FindMyDeviceServer --single-branch https://github.com/schklom/Mirror-workflows.git /fmd

FROM golang:latest AS builder
# We know from test that $GOPATH=/go
RUN go mod tidy
RUN wget https://raw.githubusercontent.com/objectbox/objectbox-go/main/install.sh
RUN chmod +x install.sh
RUN (yes | ./install.sh ;) || exit_code=$?

COPY --from=gitimport /fmd/ /go/src/fmd/
WORKDIR /go/src/fmd/cmd
RUN go build fmdserver.go
#RUN go build -ldflags "-w -s" -o /go/src/fmd/fmdserver


FROM alpine:latest
COPY --from=builder /go/src/fmd/ /fmd/

# HTTP
EXPOSE 1020/tcp
# HTTPS
EXPOSE 1008/tcp

RUN mkdir -p /fmd/objectbox
VOLUME /fmd/objectbox

CMD [ "/fmd/fmdserver" ]
