version: "3.9"

services:
  backend:
    container_name: web-whisper-backend
    volumes:
      - ./files:/app/whisper.cpp/samples
    build:
      dockerfile: ./backend.Dockerfile
      context: .
      args:
        # Valid model values: tiny, base, small, medium, large
        - WHISPER_MODEL=small
        - WHISPER_THREADS=4 # Number of threads to use during computation
        - WHISPER_PROCESSORS=1 # Number of processors to use during computation
        - CUT_MEDIA_SECONDS=0 # 0 = Disabled. Set to an integer to cut all media to that number of seconds.
        - KEEP_FILES=true # If you want to disable the transcription history, set this to false, and remove the volumes above.
  
  whisper:
    container_name: web-whisper
    ports:
      - "127.0.0.1:3000:80"
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
      args:
        - ALLOW_FILE_UPLOADS=true
        - RUN_AS_API=false # true or false. Read more here https://codeberg.org/pluja/web-whisper/wiki/Self-Hosting#running-modes-local-and-api
        - OPENAI_TOKEN=YourApiTokenHere # If you choose API, add here your api key, otherwise, leave as 'none'