version: "3.9"

services:
  backend:
    container_name: web-whisper-backend
    volumes:
      - ./files:/app/whisper.cpp/samples
    build:
      dockerfile: ./backend.Dockerfile
      context: .
      args:
        - WHISPER_MODEL=${WHISPER_MODEL}
        - CUT_MEDIA_SECONDS=${CUT_MEDIA_SECONDS}
        - WHISPER_THREADS=${WHISPER_THREADS}
        - WHISPER_PROCESSORS=${WHISPER_PROCESSORS}
        - KEEP_FILES=${KEEP_FILES}
        - ARCHITECTURE=${ARCHITECTURE}
        - OPENAI_TOKEN=${OPENAI_TOKEN}
  
  whisper:
    container_name: web-whisper
    ports:
      - "127.0.0.1:3000:80"
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
      args:
        - ALLOW_FILE_UPLOADS=${ALLOW_FILE_UPLOADS}
        - RUN_AS_API=${RUN_AS_API}