version: "3.9"

services:
  backend:
    container_name: web-whisper-backend
    #volumes: 
    #  - ./files:/app/whisper.cpp/samples
    build:
      dockerfile: ./backend.Dockerfile
      context: .
      args:
        # Valid model values: tiny, base, small, medium, large
        - WHISPER_MODEL=small
        - WHISPER_THREADS=4 # Number of threads to use during computation
        - WHISPER_PROCESSORS=1 # Number of processors to use during computation
        - CUT_MEDIA_SECONDS=10
        - KEEP_FILES=true # If you want to keep the files for later usage, and have a transcription history, turn on this variable and add the volume above.
  
  whisper:
    container_name: web-whisper
    ports:
      - "127.0.0.1:3000:80"
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
      args:
        - ALLOW_FILE_UPLOADS=true