name: fmd-server
title: FMD Server
version: '0.13.0'
license: GPL-3.0-or-later

source-code: https://gitlab.com/fmd-foss/fmd-server
issues: https://gitlab.com/fmd-foss/fmd-server/-/issues
donation: https://liberapay.com/FMD/donate
website: https://fmd-foss.org/
contact:
  - https://fmd-foss.org/about

summary: A server to communicate with the FMD Android app.
description: |
  This is the official server for FMD Android written in Go.
  The FMD app can register an account on FMD Server.
  The app can then upload its location at regular intervals.
  You can also push commands to the FMD app on your device from FMD Server, e.g. to make your device ring.
icon: snap/gui/icon.png

base: core24
grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
    build-on: [amd64]
  armhf:
    build-on: [amd64]

parts:

  # Get the general FMD Server things from the pre-compiled release.
  # The `%%hf` suffix is to remove the suffix to map "armhf" (Snap-style) to "arm" (FMD-style).
  fmd-server:
    plugin: dump
    source: https://packages.fmd-foss.org/server/fmd-server-v${SNAPCRAFT_PROJECT_VERSION}.zip
    organize:
      fmd-server: bin/fmd-server
    override-build: |
      craftctl default
      cp "${CRAFT_PART_INSTALL}/fmd-server-${CRAFT_ARCH_BUILD_FOR%%hf}" "${CRAFT_PART_INSTALL}/fmd-server"
      chmod +x "${CRAFT_PART_INSTALL}/fmd-server"
      chmod 644 "${CRAFT_PART_INSTALL}/config.example.yml"
    stage:
      - bin/fmd-server
      - config.example.yml

  # Get the Snap-specific things from the current git repo state.
  start-script:
    plugin: dump
    source: snap/
    source-type: local
    organize:
      fmd-server.sh: bin/fmd-server.sh
    override-build: |
      craftctl default
      chmod +x "${CRAFT_PART_INSTALL}/fmd-server.sh"
    stage:
      - bin/fmd-server.sh

apps:
  fmd-server:
    command: bin/fmd-server.sh serve
    daemon: simple
    restart-condition: on-failure
    plugs:
      - network
      - network-bind
