#!/usr/bin/env node
// Builds the app's exercise data from catalogue/, the one place exercises are edited.
//
//   node scripts/catalogue/build.mjs           write the generated files
//   node scripts/catalogue/build.mjs --check   fail if they are out of date (CI)
//
// catalogue/exercises/<id>.json   one exercise, in English (name, muscles, description, steps)
// catalogue/i18n/<lang>.json      { "<id>": { name, description, instructions } } per language
//
// Generated, never edited by hand:
//   frontend/src/lib/exercises-data.js        EXDB: the list the app indexes and searches
//   frontend/src/lib/exercise-muscle-map.json muscle-map corrections (catalogue "muscleMap")
//   frontend/src/instr/<lang>.js              instruction steps, loaded with the language
//   frontend/src/exercise-names/<lang>.js     translated names, loaded with the language
//   frontend/src/exercise-desc/<lang>.js      descriptions, loaded when one is shown
// and then api/coach/core/library-data.js through build-coach-assets.mjs.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import { validateCatalogue } from './validate.mjs'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const CAT = path.join(ROOT, 'catalogue')
const SRC = path.join(ROOT, 'frontend/src')
const check = process.argv.includes('--check')

const { exercises, i18n, problems } = validateCatalogue(CAT)
if (problems.length) {
  console.error(problems.join('\n'))
  process.exit(1)
}

// Old ids sort the way they always did (by name, as the dataset shipped); the list order is what
// the library shows before any filter, so it should not jump around between releases.
const rows = exercises
  .filter(e => !e.variantOf)
  .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : a.id < b.id ? -1 : 1))
  .map(e => {
    const row = {
      id: e.id, n: e.name, bp: e.bodyPart, eq: e.equipment, tg: e.target,
      mg: e.secondaryMuscles[0] || '', sm: e.secondaryMuscles,
      img: e.id + '.webp', gif: e.id + '.mp4',
    }
    if (e.category) row.cat = e.category
    if (e.femaleVariant) row.fv = e.femaleVariant
    return row
  })

const files = {}
const header = '// generated by scripts/catalogue/build.mjs from catalogue/ — do not edit\n'
files['frontend/src/lib/exercises-data.js'] = header + 'export const EXDB=' + JSON.stringify(rows) + '\n'

const muscleMap = {}
for (const e of exercises) {
  if (!e.muscleMap) continue
  const m = e.muscleMap
  muscleMap[e.id] = {
    ...(m.bodyPart ? { bp: m.bodyPart } : {}),
    ...(m.primaries ? { primaries: m.primaries } : {}),
    ...(m.secondaries ? { secondaries: m.secondaries } : {}),
    ...(m.weights ? { muscleWeights: m.weights } : {}),
  }
}
files['frontend/src/lib/exercise-muscle-map.json'] = JSON.stringify(muscleMap, null, 1) + '\n'

const pack = (obj) => header + 'export default ' + JSON.stringify(obj) + '\n'
const byId = (pick) => Object.fromEntries(exercises.filter(e => !e.variantOf).map(e => [e.id, pick(e)]).filter(([, v]) => v && (!Array.isArray(v) || v.length)))
files['frontend/src/instr/en.js'] = pack(byId(e => e.instructions))
files['frontend/src/exercise-desc/en.js'] = pack(byId(e => e.description))
for (const [lang, rowsOf] of Object.entries(i18n)) {
  const pick = key => Object.fromEntries(Object.entries(rowsOf).filter(([, r]) => r[key] && (!Array.isArray(r[key]) || r[key].length)).map(([id, r]) => [id, r[key]]))
  const instr = pick('instructions'), names = pick('name'), desc = pick('description')
  if (Object.keys(instr).length) files[`frontend/src/instr/${lang}.js`] = pack(instr)
  if (Object.keys(names).length) files[`frontend/src/exercise-names/${lang}.js`] = pack(names)
  if (Object.keys(desc).length) files[`frontend/src/exercise-desc/${lang}.js`] = pack(desc)
}

// Which languages have instruction and name packs, for i18n-core (a pack may be partial: anything
// it lacks falls back to English one exercise at a time).
const packLangs = dir => ['en', ...Object.keys(files).filter(f => f.startsWith(`frontend/src/${dir}/`)).map(f => f.slice(`frontend/src/${dir}/`.length, -3)).filter(l => l !== 'en').sort()]
files['frontend/src/lib/catalogue-langs.js'] = header +
  `export const INSTR_LANGS = ${JSON.stringify(packLangs('instr'))}\n` +
  `export const EXERCISE_NAME_LANGS = ${JSON.stringify(packLangs('exercise-names').filter(l => l !== 'en'))}\n`

// catalogue/browse/: one page per body part with each exercise's still, so contributors can see
// what an id is without running the app. GitHub renders these Markdown tables with the pictures.
const slug = s => s.replace(/\s+/g, '-')
const visible = exercises.filter(e => !e.variantOf)
const parts = [...new Set(visible.map(e => e.bodyPart))].sort()
const cell = s => String(s || '').replace(/\|/g, '\\|')
files['catalogue/browse/README.md'] = '# Browse the catalogue\n\n' +
  'Generated by `scripts/catalogue/build.mjs`, do not edit. Pictures © Gym visual, licensed for openGym only (see [NOTICE](../media/NOTICE.md)).\n\n' +
  parts.map(p => `- [${p}](${slug(p)}.md) (${visible.filter(e => e.bodyPart === p).length})`).join('\n') + '\n'
for (const p of parts) {
  const list = visible.filter(e => e.bodyPart === p).sort((a, b) => (a.name < b.name ? -1 : 1))
  files[`catalogue/browse/${slug(p)}.md`] = `# ${p}\n\nGenerated by \`scripts/catalogue/build.mjs\`, do not edit. Click an id to edit that exercise. ` +
    'Pictures © Gym visual, licensed for openGym only (see [NOTICE](../media/NOTICE.md)).\n\n' +
    '| | id | name | equipment | target |\n|---|---|---|---|---|\n' +
    list.map(e => `| <img src="../media/still/${e.id}.webp" width="90" height="90" alt=""> | [${e.id}](../exercises/${e.id}.json) | ${cell(e.name)} | ${cell(e.equipment)} | ${cell(e.target)} |`).join('\n') + '\n'
}

let stale = []
for (const [rel, body] of Object.entries(files)) {
  const p = path.join(ROOT, rel)
  const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null
  if (cur === body) continue
  stale.push(rel)
  if (!check) { fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, body) }
}
if (check) {
  if (stale.length) { console.error('Out of date, run node scripts/catalogue/build.mjs:\n  ' + stale.join('\n  ')); process.exit(1) }
  console.log(`catalogue: ${rows.length} exercises, generated files up to date`)
} else {
  execFileSync(process.execPath, [path.join(ROOT, 'scripts/build-coach-assets.mjs')], { stdio: 'inherit' })
  console.log(`catalogue: ${rows.length} exercises, ${stale.length} file(s) rewritten`)
}
