// Code generated by ObjectBox; DO NOT EDIT.

package user

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(UserBinding)
	model.LastEntityId(1, 3954602988193931325)
	model.LastIndexId(1, 2944041920753964299)

	return model
}
