// generated by scripts/catalogue/build.mjs from catalogue/ — do not edit
export const INSTR_LANGS = ["en","ar","es","fr","hi","hu","it","ko","pl","pt-BR","ru","tr","zh","zh-TW"]
export const EXERCISE_NAME_LANGS = ["ar","bn","de","es","fr","hi","hu","it","ko","pl","pt-BR","ru","th","tr","uk","zh","zh-TW"]
