// GENERATED by scripts/build-nudge-copy.mjs from frontend/src/lib/nudge.js and frontend/src/locales.
// Do not edit by hand: change the frontend strings and run the script again.
export const NUDGE_COPY = {
  "en": {
    "friendly": {
      "title": "Everything okay?",
      "lines": [
        "{0} is still waiting. What’s up?",
        "No {0} today? Even a short session tomorrow counts.",
        "Rough day? {0} will keep. Tomorrow is a fresh start.",
        "Hey, {0} didn’t happen today. All good?"
      ]
    },
    "guilt": {
      "title": "I miss you",
      "lines": [
        "{0} waited by the door all evening. For you.",
        "The barbell asked about you today. I didn’t know what to say.",
        "Was it something I said? {0} misses you.",
        "I saved you a spot on the bench. It’s still empty."
      ]
    },
    "drill": {
      "title": "Attention, recruit!",
      "lines": [
        "Your gains are packing their bags. {0} tomorrow, no excuses!",
        "{0} doesn’t do itself, recruit. Move it!",
        "Excuses don’t lift weights. Report for {0} tomorrow!",
        "Your muscles filed a missing-person report. Show up for {0}!"
      ]
    }
  },
  "ar": {
    "friendly": {
      "title": "هل كل شيء على ما يرام؟",
      "lines": [
        "{0} ما زال ينتظرك. ما الأمر؟",
        "لا {0} اليوم؟ حتى جلسة قصيرة غدًا تُحسب.",
        "يوم صعب؟ {0} يمكنه الانتظار. غدًا بداية جديدة.",
        "مرحبًا، لم يحدث {0} اليوم. هل كل شيء بخير؟"
      ]
    },
    "guilt": {
      "title": "اشتقت إليك",
      "lines": [
        "{0} انتظرك عند الباب طوال المساء. أنت بالذات.",
        "سأل عنك البار اليوم. لم أعرف ماذا أقول.",
        "هل قلت شيئًا أزعجك؟ {0} مشتاق إليك.",
        "حجزت لك مكانًا على المقعد. ما زال فارغًا."
      ]
    },
    "drill": {
      "title": "انتباه أيها المجنّد!",
      "lines": [
        "مكاسبك تحزم حقائبها. {0} غدًا، بلا أعذار!",
        "{0} لن ينجز نفسه أيها المجنّد. تحرّك!",
        "الأعذار لا ترفع الأوزان. احضر غدًا إلى {0}!",
        "عضلاتك أبلغت عن فقدانك. احضر إلى {0}!"
      ]
    }
  },
  "bn": {
    "friendly": {
      "title": "সব ঠিক আছে তো?",
      "lines": [
        "{0} এখনও অপেক্ষা করছে। কী হলো?",
        "আজ {0} হলো না? কাল ছোট একটা সেশনও কাজে দেবে।",
        "কঠিন দিন গেল? {0} অপেক্ষা করবে। কাল নতুন শুরু।",
        "এই যে, আজ {0} হলো না। সব ঠিক তো?"
      ]
    },
    "guilt": {
      "title": "তোমাকে মিস করছি",
      "lines": [
        "{0} সারা সন্ধ্যা দরজার পাশে অপেক্ষা করেছে। শুধু তোমার জন্য।",
        "বারবেল আজ তোমার খোঁজ নিল। আমি কী বলব বুঝতে পারিনি।",
        "আমি কি কিছু বলেছি? {0} তোমাকে মিস করছে।",
        "বেঞ্চে তোমার জন্য জায়গা রেখেছিলাম। এখনও খালি।"
      ]
    },
    "drill": {
      "title": "সাবধান, রিক্রুট!",
      "lines": [
        "তোমার গেইনস ব্যাগ গোছাচ্ছে। কাল {0}, কোনো অজুহাত নয়!",
        "{0} নিজে নিজে হয় না, রিক্রুট। নড়ো!",
        "অজুহাত ওজন তোলে না। কাল {0}-এর জন্য হাজির হও!",
        "তোমার পেশিরা নিখোঁজ ডায়েরি করেছে। {0}-এর জন্য হাজির হও!"
      ]
    }
  },
  "de": {
    "friendly": {
      "title": "Alles okay?",
      "lines": [
        "{0} wartet noch auf dich. Was ist los?",
        "Heute kein {0}? Auch eine kurze Einheit morgen zählt.",
        "Harter Tag? {0} läuft nicht weg. Morgen ist ein neuer Anfang.",
        "Hey, {0} ist heute ausgefallen. Alles gut?"
      ]
    },
    "guilt": {
      "title": "Ich vermisse dich",
      "lines": [
        "{0} hat den ganzen Abend an der Tür gewartet. Auf dich.",
        "Die Langhantel hat heute nach dir gefragt. Ich wusste nicht, was ich sagen soll.",
        "War es etwas, das ich gesagt habe? {0} vermisst dich.",
        "Ich habe dir einen Platz auf der Bank freigehalten. Er ist immer noch leer."
      ]
    },
    "drill": {
      "title": "Achtung, Rekrut!",
      "lines": [
        "Deine Gains packen schon die Koffer. {0} morgen, keine Ausreden!",
        "{0} macht sich nicht von allein, Rekrut. Bewegung!",
        "Ausreden stemmen keine Gewichte. Morgen trittst du zu {0} an!",
        "Deine Muskeln haben eine Vermisstenanzeige aufgegeben. Antreten zu {0}!"
      ]
    }
  },
  "es": {
    "friendly": {
      "title": "¿Todo bien?",
      "lines": [
        "{0} sigue esperando. ¿Qué pasa?",
        "¿Hoy no hubo {0}? Mañana, hasta una sesión corta cuenta.",
        "¿Día difícil? {0} puede esperar. Mañana empiezas de nuevo.",
        "Oye, hoy no hubo {0}. ¿Todo bien?"
      ]
    },
    "guilt": {
      "title": "Te echo de menos",
      "lines": [
        "{0} te esperó en la puerta toda la tarde. A ti.",
        "La barra preguntó por ti hoy. No supe qué decirle.",
        "¿Fue algo que dije? {0} te echa de menos.",
        "Te guardé un sitio en el banco. Sigue vacío."
      ]
    },
    "drill": {
      "title": "¡Atención, recluta!",
      "lines": [
        "Tus ganancias están haciendo las maletas. ¡{0} mañana, sin excusas!",
        "{0} no se hace solo, recluta. ¡Muévete!",
        "Las excusas no levantan pesas. ¡Mañana te presentas a {0}!",
        "Tus músculos pusieron una denuncia por desaparición. ¡Preséntate a {0}!"
      ]
    }
  },
  "fr": {
    "friendly": {
      "title": "Tout va bien ?",
      "lines": [
        "{0} t’attend toujours. Que se passe-t-il ?",
        "Pas de {0} aujourd’hui ? Même une courte séance demain compte.",
        "Journée difficile ? {0} peut attendre. Demain est un nouveau départ.",
        "Hé, {0} n’a pas eu lieu aujourd’hui. Tout va bien ?"
      ]
    },
    "guilt": {
      "title": "Tu me manques",
      "lines": [
        "{0} t’a attendu à la porte toute la soirée. Toi.",
        "La barre a demandé de tes nouvelles aujourd’hui. Je n’ai pas su quoi lui dire.",
        "C’est quelque chose que j’ai dit ? {0} s’ennuie de toi.",
        "Je t’ai gardé une place sur le banc. Elle est toujours vide."
      ]
    },
    "drill": {
      "title": "Garde-à-vous, recrue !",
      "lines": [
        "Tes gains font leurs valises. {0} demain, sans excuses !",
        "{0} ne va pas se faire tout seul, recrue. Au pas de course !",
        "Les excuses ne soulèvent pas de poids. Présente-toi demain pour {0} !",
        "Tes muscles ont signalé ta disparition. Présente-toi pour {0} !"
      ]
    }
  },
  "hi": {
    "friendly": {
      "title": "सब ठीक है?",
      "lines": [
        "{0} अब भी इंतज़ार कर रहा है। क्या हुआ?",
        "आज {0} नहीं हुआ? कल एक छोटा सेशन भी गिना जाएगा।",
        "मुश्किल दिन था? {0} इंतज़ार कर लेगा। कल नई शुरुआत है।",
        "अरे, आज {0} नहीं हुआ। सब ठीक है?"
      ]
    },
    "guilt": {
      "title": "आपकी याद आ रही है",
      "lines": [
        "{0} पूरी शाम दरवाज़े पर आपका इंतज़ार करता रहा।",
        "आज बारबेल ने आपके बारे में पूछा। मुझे समझ नहीं आया क्या कहूँ।",
        "क्या मैंने कुछ गलत कहा? {0} को आपकी याद आ रही है।",
        "मैंने बेंच पर आपके लिए जगह रखी थी। वह अब भी खाली है।"
      ]
    },
    "drill": {
      "title": "सावधान, रंगरूट!",
      "lines": [
        "आपके गेन्स बोरिया-बिस्तर बाँध रहे हैं। कल {0}, कोई बहाना नहीं!",
        "{0} अपने आप नहीं होगा, रंगरूट। चलो, हिलो!",
        "बहाने वज़न नहीं उठाते। कल {0} के लिए हाज़िर हो!",
        "आपकी मांसपेशियों ने गुमशुदगी की रिपोर्ट लिखाई है। {0} के लिए हाज़िर हो!"
      ]
    }
  },
  "hu": {
    "friendly": {
      "title": "Minden rendben?",
      "lines": [
        "A(z) {0} még mindig vár. Mi a helyzet?",
        "Ma nem volt {0}? Holnap egy rövid edzés is számít.",
        "Nehéz nap? A(z) {0} megvár. Holnap új kezdet.",
        "Hé, ma elmaradt a(z) {0}. Minden oké?"
      ]
    },
    "guilt": {
      "title": "Hiányzol",
      "lines": [
        "A(z) {0} egész este az ajtóban várt. Rád.",
        "A rúd ma rólad kérdezett. Nem tudtam, mit mondjak.",
        "Valami rosszat mondtam? A(z) {0} hiányol téged.",
        "Foglaltam neked helyet a padon. Még mindig üres."
      ]
    },
    "drill": {
      "title": "Vigyázz, újonc!",
      "lines": [
        "Az eredményeid már pakolnak. Holnap {0}, nincs kifogás!",
        "A(z) {0} nem csinálja meg magát, újonc. Mozgás!",
        "A kifogások nem emelnek súlyt. Holnap jelentkezel: {0}!",
        "Az izmaid eltűntként jelentettek. Jelentkezz: {0}!"
      ]
    }
  },
  "it": {
    "friendly": {
      "title": "Tutto bene?",
      "lines": [
        "{0} ti sta ancora aspettando. Che succede?",
        "Niente {0} oggi? Anche una sessione breve domani conta.",
        "Giornata dura? {0} può aspettare. Domani si ricomincia.",
        "Ehi, oggi {0} è saltato. Tutto a posto?"
      ]
    },
    "guilt": {
      "title": "Mi manchi",
      "lines": [
        "{0} ti ha aspettato alla porta tutta la sera. Proprio te.",
        "Il bilanciere oggi ha chiesto di te. Non sapevo cosa dirgli.",
        "Ho detto qualcosa di sbagliato? {0} sente la tua mancanza.",
        "Ti ho tenuto un posto sulla panca. È ancora vuoto."
      ]
    },
    "drill": {
      "title": "Attenti, recluta!",
      "lines": [
        "I tuoi progressi stanno facendo le valigie. {0} domani, niente scuse!",
        "{0} non si fa da solo, recluta. Muoviti!",
        "Le scuse non sollevano pesi. Domani ti presenti a {0}!",
        "I tuoi muscoli hanno denunciato la tua scomparsa. Presentati a {0}!"
      ]
    }
  },
  "ko": {
    "friendly": {
      "title": "괜찮으세요?",
      "lines": [
        "{0}이(가) 아직 기다리고 있어요. 무슨 일 있어요?",
        "오늘은 {0} 안 했나요? 내일은 짧게라도 하면 돼요.",
        "힘든 하루였나요? {0}은(는) 기다려 줄 거예요. 내일 다시 시작해요.",
        "저기요, 오늘 {0}을(를) 못 했네요. 괜찮아요?"
      ]
    },
    "guilt": {
      "title": "보고 싶어요",
      "lines": [
        "{0}이(가) 저녁 내내 문 앞에서 기다렸어요. 당신을요.",
        "오늘 바벨이 당신 안부를 물었어요. 뭐라고 해야 할지 몰랐어요.",
        "제가 뭐 잘못 말했나요? {0}이(가) 당신을 보고 싶어 해요.",
        "벤치에 자리를 맡아 뒀어요. 아직 비어 있어요."
      ]
    },
    "drill": {
      "title": "차렷, 훈련병!",
      "lines": [
        "근손실이 짐을 싸고 있다. 내일 {0}, 핑계는 없다!",
        "{0}은(는) 저절로 되지 않는다, 훈련병. 움직여!",
        "핑계는 무게를 들지 않는다. 내일 {0}에 집합!",
        "근육들이 실종 신고를 냈다. {0}에 출석하라!"
      ]
    }
  },
  "pl": {
    "friendly": {
      "title": "Wszystko w porządku?",
      "lines": [
        "Trening „{0}” wciąż czeka. Co się dzieje?",
        "Dziś bez treningu „{0}”? Jutro nawet krótka sesja się liczy.",
        "Ciężki dzień? Trening „{0}” poczeka. Jutro nowy start.",
        "Hej, trening „{0}” dziś nie wyszedł. Wszystko dobrze?"
      ]
    },
    "guilt": {
      "title": "Tęsknię za tobą",
      "lines": [
        "Trening „{0}” czekał na ciebie przy drzwiach cały wieczór. Właśnie na ciebie.",
        "Sztanga pytała dziś o ciebie. Nie wiedziałem, co powiedzieć.",
        "Czy to przez coś, co powiedziałem? Trening „{0}” tęskni za tobą.",
        "Zająłem ci miejsce na ławce. Wciąż jest puste."
      ]
    },
    "drill": {
      "title": "Baczność, rekrucie!",
      "lines": [
        "Twoje postępy pakują walizki. Jutro „{0}”, bez wymówek!",
        "Trening „{0}” sam się nie zrobi, rekrucie. Ruszaj się!",
        "Wymówki nie podnoszą ciężarów. Jutro meldujesz się na „{0}”!",
        "Twoje mięśnie zgłosiły twoje zaginięcie. Stawić się na „{0}”!"
      ]
    }
  },
  "pt": {
    "friendly": {
      "title": "Está tudo bem?",
      "lines": [
        "{0} ainda está à tua espera. Então?",
        "Hoje não houve {0}? Amanhã até um treino curto conta.",
        "Dia difícil? {0} pode esperar. Amanhã é um novo começo.",
        "Olha, hoje não houve {0}. Está tudo bem?"
      ]
    },
    "guilt": {
      "title": "Tenho saudades tuas",
      "lines": [
        "{0} esperou por ti à porta a noite toda. Por ti.",
        "A barra perguntou por ti hoje. Não soube o que lhe dizer.",
        "Foi alguma coisa que eu disse? {0} tem saudades tuas.",
        "Guardei-te um lugar no banco. Continua vazio."
      ]
    },
    "drill": {
      "title": "Sentido, recruta!",
      "lines": [
        "Os teus ganhos estão a fazer as malas. {0} amanhã, sem desculpas!",
        "{0} não se faz sozinho, recruta. Mexe-te!",
        "Desculpas não levantam pesos. Amanhã apresentas-te para {0}!",
        "Os teus músculos deram-te como desaparecido. Apresenta-te para {0}!"
      ]
    }
  },
  "pt-BR": {
    "friendly": {
      "title": "Está tudo bem?",
      "lines": [
        "{0} ainda está esperando você. E aí?",
        "Hoje não teve {0}? Amanhã até um treino curto conta.",
        "Dia difícil? {0} pode esperar. Amanhã é um novo começo.",
        "Ei, hoje não teve {0}. Tudo certo?"
      ]
    },
    "guilt": {
      "title": "Estou com saudade de você",
      "lines": [
        "{0} esperou você na porta a noite toda. Você.",
        "A barra perguntou de você hoje. Não soube o que dizer.",
        "Foi alguma coisa que eu disse? {0} está com saudade de você.",
        "Guardei um lugar no banco para você. Continua vazio."
      ]
    },
    "drill": {
      "title": "Sentido, recruta!",
      "lines": [
        "Seus ganhos estão fazendo as malas. {0} amanhã, sem desculpas!",
        "{0} não se faz sozinho, recruta. Mexa-se!",
        "Desculpa não levanta peso. Amanhã você se apresenta para {0}!",
        "Seus músculos registraram seu desaparecimento. Apresente-se para {0}!"
      ]
    }
  },
  "ru": {
    "friendly": {
      "title": "Всё в порядке?",
      "lines": [
        "Тренировка «{0}» всё ещё ждёт. Что случилось?",
        "Сегодня без тренировки «{0}»? Завтра засчитается даже короткая.",
        "Тяжёлый день? Тренировка «{0}» подождёт. Завтра будет новый старт.",
        "Эй, тренировка «{0}» сегодня не состоялась. Всё хорошо?"
      ]
    },
    "guilt": {
      "title": "Я скучаю по вам",
      "lines": [
        "Тренировка «{0}» весь вечер ждала вас у двери. Именно вас.",
        "Штанга сегодня спрашивала о вас. Я не знал, что ответить.",
        "Я что-то не то сказал? Тренировка «{0}» скучает по вам.",
        "Я занял вам место на скамье. Оно всё ещё пустое."
      ]
    },
    "drill": {
      "title": "Смирно, новобранец!",
      "lines": [
        "Ваши достижения пакуют чемоданы. Завтра «{0}», без отговорок!",
        "Тренировка «{0}» сама себя не сделает, новобранец. Шевелитесь!",
        "Отговорки не поднимают веса. Завтра явиться на «{0}»!",
        "Ваши мышцы подали заявление о пропаже. Явиться на «{0}»!"
      ]
    }
  },
  "th": {
    "friendly": {
      "title": "ทุกอย่างโอเคไหม?",
      "lines": [
        "{0} ยังรอคุณอยู่นะ เป็นอะไรหรือเปล่า?",
        "วันนี้ไม่มี {0} เหรอ? พรุ่งนี้แค่เล่นสั้นๆ ก็นับแล้ว",
        "วันนี้เหนื่อยเหรอ? {0} รอได้ พรุ่งนี้เริ่มใหม่",
        "เฮ้ วันนี้ไม่ได้เล่น {0} ทุกอย่างโอเคไหม?"
      ]
    },
    "guilt": {
      "title": "คิดถึงคุณนะ",
      "lines": [
        "{0} รอคุณอยู่ที่ประตูทั้งคืน รอคุณคนเดียว",
        "วันนี้บาร์เบลถามถึงคุณ ฉันไม่รู้จะตอบว่าอะไร",
        "ฉันพูดอะไรผิดไปหรือเปล่า? {0} คิดถึงคุณนะ",
        "ฉันจองที่บนม้านั่งไว้ให้คุณ ตอนนี้ยังว่างอยู่เลย"
      ]
    },
    "drill": {
      "title": "แถวตรง พลทหาร!",
      "lines": [
        "กล้ามของคุณกำลังเก็บกระเป๋าหนี พรุ่งนี้ {0} ห้ามมีข้ออ้าง!",
        "{0} ไม่ทำตัวเองหรอก พลทหาร เคลื่อนไหว!",
        "ข้ออ้างยกน้ำหนักไม่ได้ พรุ่งนี้มารายงานตัวที่ {0}!",
        "กล้ามเนื้อของคุณแจ้งคนหายแล้ว มารายงานตัวที่ {0}!"
      ]
    }
  },
  "tr": {
    "friendly": {
      "title": "Her şey yolunda mı?",
      "lines": [
        "{0} hâlâ seni bekliyor. Ne oldu?",
        "Bugün {0} yok mu? Yarın kısa bir seans bile sayılır.",
        "Zor bir gün mü? {0} bekleyebilir. Yarın yeni bir başlangıç.",
        "Hey, {0} bugün olmadı. Her şey yolunda mı?"
      ]
    },
    "guilt": {
      "title": "Seni özledim",
      "lines": [
        "{0} bütün akşam kapıda seni bekledi. Seni.",
        "Halter bugün seni sordu. Ne diyeceğimi bilemedim.",
        "Bir şey mi dedim? {0} seni özledi.",
        "Sana sehpada yer ayırdım. Hâlâ boş."
      ]
    },
    "drill": {
      "title": "Hazır ol, acemi!",
      "lines": [
        "Kazanımların bavul topluyor. Yarın {0}, bahane yok!",
        "{0} kendi kendine yapılmaz, acemi. Kımılda!",
        "Bahaneler ağırlık kaldırmaz. Yarın {0} için hazır ol!",
        "Kasların kayıp ilanı verdi. {0} için içtimaya gel!"
      ]
    }
  },
  "uk": {
    "friendly": {
      "title": "Усе гаразд?",
      "lines": [
        "Тренування «{0}» досі чекає. Що сталося?",
        "Сьогодні без тренування «{0}»? Завтра зарахується навіть коротке.",
        "Важкий день? Тренування «{0}» почекає. Завтра буде новий старт.",
        "Гей, тренування «{0}» сьогодні не відбулося. Усе добре?"
      ]
    },
    "guilt": {
      "title": "Я сумую за тобою",
      "lines": [
        "Тренування «{0}» весь вечір чекало на тебе біля дверей. Саме на тебе.",
        "Штанга сьогодні питала про тебе. Я не знав, що сказати.",
        "Я щось не те сказав? Тренування «{0}» сумує за тобою.",
        "Я зайняв тобі місце на лаві. Воно досі порожнє."
      ]
    },
    "drill": {
      "title": "Струнко, новобранцю!",
      "lines": [
        "Твої здобутки пакують валізи. Завтра «{0}», без відмовок!",
        "Тренування «{0}» саме себе не зробить, новобранцю. Ворушися!",
        "Відмовки не піднімають ваги. Завтра з’явитися на «{0}»!",
        "Твої м’язи заявили про твоє зникнення. З’явитися на «{0}»!"
      ]
    }
  },
  "zh": {
    "friendly": {
      "title": "一切还好吗？",
      "lines": [
        "{0}还在等你。怎么了？",
        "今天没练{0}？明天哪怕练一小会儿也算数。",
        "今天不顺？{0}可以等。明天重新开始。",
        "嘿，今天的{0}没练成。一切都好吗？"
      ]
    },
    "guilt": {
      "title": "我想你了",
      "lines": [
        "{0}在门口等了你一整晚。就等你。",
        "杠铃今天问起你了。我不知道该怎么说。",
        "是我说错什么了吗？{0}想你了。",
        "我在卧推凳上给你留了位置。现在还空着。"
      ]
    },
    "drill": {
      "title": "立正，新兵！",
      "lines": [
        "你的增肌成果正在收拾行李。明天{0}，不许找借口！",
        "{0}不会自己完成，新兵。动起来！",
        "借口举不起重量。明天准时报到练{0}！",
        "你的肌肉已经报了失踪。马上来练{0}！"
      ]
    }
  },
  "zh-TW": {
    "friendly": {
      "title": "一切還好嗎？",
      "lines": [
        "{0} 還在等你。怎麼了？",
        "今天沒練 {0}？明天就算練一下下也算數。",
        "今天不順？{0} 可以等。明天重新開始。",
        "嘿，今天的 {0} 沒練到。一切都好嗎？"
      ]
    },
    "guilt": {
      "title": "我好想你",
      "lines": [
        "{0} 在門口等了你一整晚。就等你。",
        "槓鈴今天問起你了。我不知道該怎麼回答。",
        "是我說錯什麼了嗎？{0} 很想你。",
        "我在臥推椅上幫你留了位置。現在還空著。"
      ]
    },
    "drill": {
      "title": "立正，菜鳥！",
      "lines": [
        "你的訓練成果正在打包行李。明天 {0}，不准找藉口！",
        "{0} 不會自己完成，菜鳥。動起來！",
        "藉口舉不起重量。明天準時報到練 {0}！",
        "你的肌肉已經報案協尋你了。馬上來練 {0}！"
      ]
    }
  }
};
