name: Download+Release Tasker

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'schklom/Tasker-apk'
          ref: 'main' # branch

      - name: Get apk from Google Drive
        run: |
          filename="./Tasker.28.Direct.apk"
          echo "filename=${filename}" >> $GITHUB_ENV
          fileid=${{ secrets.TASKER_GOOGLE_DRIVE_FILE_ID }}
          url="https://drive.google.com/uc?export=download&confirm=t&id=${fileid}"
          curl -L "https://drive.google.com/uc?export=download&confirm=t&id=${fileid}" -o ${filename}
      
      - name: Store md5 hash of new apk
        run: md5sum "${{ env.filename }}" | cut -d " " -f 1 > hash_new_file
      
      - name: Read current and new hash of apk
        run: |
          echo "current_hash=$(cat hash_current_file)" >> $GITHUB_ENV
          echo "new_hash=$(cat hash_new_file)" >> $GITHUB_ENV
      
      - name: Record last update date and update current hash
        if: ${{ env.current_hash }} != ${{ env.new_hash }}
        run: |
          date +%Y%m%d > last_update_date
          mv hash_new_file hash_current_file
      
      - name: DEBUG
        run: |
          ls -alh ./
          echo "current hash=${{ env.current_hash }}"
          echo "new hash=${{ env.new_hash }}"
      
      - name: Commit and push the change
        if: ${{ env.current_hash }} != ${{ env.new_hash }}
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Update the apk, its hash, and update date
        
      - name: Release apk if hashes are different
        if: ${{ env.current_hash }} != ${{ env.new_hash }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "$(cat last_update_date)"
          body: "New version of Tasker Direct Purchase"
          files: "${{ env.filename }}"
