name: Download+Release tt-rss-android

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 0 * * SUN,WED' # Google causes problems sometimes when downloads are too frequent

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  get_commits:
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    outputs:
      LOCAL: ${{ steps.commits.outputs.SETLOCAL }}
      REMOTE: ${{ steps.commits.outputs.SETREMOTE }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'schklom/tt-rss-android'
          ref: 'master' # branch
      - name: set local and remote latest commit as environment variables
        id: commits
        # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
        # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
        run: |
          echo "SETREMOTE=$(git ls-remote https://gitlab.tt-rss.org/tt-rss/tt-rss-android HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL=$(git ls-remote https://github.com/schklom/tt-rss-android HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT

  repo_sync_master:
    needs: [get_commits]
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    if: ${{needs.get_commits.outputs.LOCAL}} != ${{needs.get_commits.outputs.REMOTE}}
    steps:
      - name: repo-sync master branch
        uses: wei/git-sync@v3
        with:
          source_repo: "https://gitlab.tt-rss.org/tt-rss/tt-rss-android.git"
          source_branch: "refs/remotes/source/*"
          #source_branch: "master"
          ####destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_repo: "git@github.com:schklom/tt-rss-android.git"
          ####destination_branch: "Gadgetbridge-osmand-experiments"
          destination_branch: "refs/heads/*"
          #source_branch: "refs/tags/*"
          #destination_branch: "refs/tags/*"
          destination_ssh_private_key: ${{ secrets.GITSYNCACTION }}

  build_ttrss_on_master:
    needs: [repo_sync_master]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'schklom/tt-rss-android'
          ####ref: 'Gadgetbridge-osmand-experiments' # branch
          #ref: 'osmand-experiments' # branch
          ref: 'master' # branch
      - name: Update package lists
        run: sudo apt-get update
      # https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation
      - name: Setup JDK+Android
        run: sudo apt-get install openjdk-11-jdk git adb -y
      - name: Gradlew executable
        run: chmod +x gradlew
      - name: Build apk
        run: ./gradlew --no-daemon assembleDebug
      - name: LS
        run: ls -AlhR ./
      #- name: Delete previous release
      #  run: git push --delete origin Gadgetbridge-osmand-experiments-${{ needs.get_commit_and_tag.outputs.LOCALTAG }}
      
      - name: Set the version
        id: step_one
        run: |
          ver=$(git ls-remote --tags --sort="version:refname" https://gitlab.tt-rss.org/tt-rss/tt-rss-android | tail -n 1 | awk '{ print $2 }' | cut -d / -f 3)
          echo "version=${ver}" >> $GITHUB_ENV
      
      - name: Release apk
        uses: softprops/action-gh-release@v1
        with:
          ####tag_name: Gadgetbridge-osmand-experiments-${{ needs.get_commit_and_tag.outputs.REMOTETAG }}
          tag_name: "${{ env.version }}"
          body: "app-main-debug.apk is the tt-rss-android file"
          #files: |
            # ./app/build/outputs/apk/app-debug.apk
          #files: ./app/build/outputs/apk/main/release/app-main-release-unsigned.apk
          #files: ./app/build/outputs/apk/main/debug/app-main-debug.apk
          files: ./org.fox.ttrss/build/outputs/apk/debug/org.fox.ttrss-debug.apk
          repository: "schklom/tt-rss-android"
          token: ${{ secrets.PAT_GITHUB_ACTION }}

