name: Gadgetbridge-osm repo sync

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  repo_sync_master:
    #if: ${{ false }}
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    #if: needs.get_commit_and_tag.outputs.LOCALTAG != needs.get_commit_and_tag.outputs.REMOTETAG || needs.get_commit_and_tag.outputs.LOCALCOMMIT != needs.get_commit_and_tag.outputs.REMOTECOMMIT
    steps:
      - name: repo-sync master branch
        uses: wei/git-sync@v3
        with:
          source_repo: "https://codeberg.org/Freeyourgadget/Gadgetbridge.git"
          source_branch: "refs/remotes/source/*"
          ####destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_repo: "git@github.com:schklom/Gadgetbridge-osm.git"
          ####destination_branch: "Gadgetbridge-osmand-experiments"
          destination_branch: "refs/heads/*"
          destination_ssh_private_key: ${{ secrets.GITSYNCACTION }}
  
