name: Gadgetbridge-osm build+release

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  build_gadgetbridge:
    #needs: [get_commit_and_tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'schklom/Gadgetbridge-osm'
          ####ref: 'Gadgetbridge-osmand-experiments' # branch
          ref: 'osmand-experiments' # branch
          #ref: 'master' # branch
      # https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Developer-Documentation
      - name: Setup JDK+Android
        run: sudo apt-get install openjdk-11-jdk git adb -y
      - name: Build apk
        run: ./gradlew --no-daemon assembleDebug
      - name: LS
        run: ls -AlhR app/build/outputs
      #- name: Delete previous release
      #  run: git push --delete origin Gadgetbridge-osmand-experiments-${{ needs.get_commit_and_tag.outputs.LOCALTAG }}
      - name: Release apk
        uses: softprops/action-gh-release@v1
        with:
          ####tag_name: Gadgetbridge-osmand-experiments-${{ needs.get_commit_and_tag.outputs.REMOTETAG }}
          tag_name: Gadgetbridge-osmand-experiments
          #files: ./app/build/outputs/apk/app-debug.apk
          files: |
            ./app/build/outputs/apk/main/release/app-main-release-unsigned.apk
