name: Sync test
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v2
        with:
          source_repo: "https://gitlab.com/stormking/feedropolis.git"
          source_branch: "master"
          destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_branch: "Feedropolis"
          ssh_private_key: ${{ secrets.GITSYNCACTION }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'Feedropolis'

      # Runs a single command using the runners shell
      - name: Add python and build-essential to apt-get install
        run: |
          id
          ls -alh
          cat Dockerfile
          sed -i '/apt-get install -y/s/$/ python3 build-essential/' Dockerfile
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Add python and build-essential to apt-get install, for a linux/arm/v7 image
