name: Sync+build+push Feedropolis
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      with:
        source_repo: "https://gitlab.com/stormking/feedropolis.git"
        source_branch: "master"
        destination_repo: "git@github.com:schklom/Mirror-workflows.git"
        destination_branch: "Feedropolis"
        ssh_private_key: ${{ secrets.GITSYNCACTION }}
  buildandpush:
    needs: [repo-sync]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'Feedropolis' # branch
      - name: Add python and build-essential to apt-get install, for a linux/arm/v7 image
        run: sed -i '/apt-get install -y/s/$/ python3 build-essential/' Dockerfile
      # https://github.com/marketplace/actions/git-auto-commit
      - name: Commit and push the change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add python and build-essential to apt-get install, for a linux/arm/v7 image
      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        #with:
          #image: tonistiigi/binfmt:latest
          #platforms: all
          #platforms: arm/v7
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        #with:
          #install: true
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push Feedropolis
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/arm/v7
          pull: true
          push: true
          tags: |
            schklom/feedropolis:latest
          #labels: ${{ steps.docker_meta.outputs.labels }}
