name: Sync+build+push Matterbridge

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    outputs:
      LOCAL: ${{ steps.commits.outputs.SETLOCAL }}
      REMOTE: ${{ steps.commits.outputs.SETREMOTE }} 
    steps:
      - name: set commits as environment variables
        id: commits
        # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
        # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
        run: |
          echo "SETREMOTE=$(git ls-remote https://github.com/42wim/matterbridge.git HEAD | awk '{ print $1 }')" >> $GITHUB_OUTPUT
          echo "SETLOCAL=$(git ls-remote https://github.com/schklom/Mirror-workflows.git refs/heads/Matterbridge | awk '{ print $1 }')" >> $GITHUB_OUTPUT
  
  repo-sync:
    needs: [get_commits]
    runs-on: ubuntu-latest
    # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
    if: needs.get_commits.outputs.LOCAL != needs.get_commits.outputs.REMOTE
    steps:
      - name: repo-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://github.com/42wim/matterbridge.git"
          source_branch: "master"
          destination_repo: "git@github.com:schklom/Mirror-workflows.git"
          destination_branch: "Matterbridge"
          ssh_private_key: ${{ secrets.GITSYNCACTION }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'Matterbridge'
      - name: get most recent commit id on original repo, for next comparison on sync
        run: git ls-remote https://github.com/42wim/matterbridge.git HEAD | awk '{ print $1 }' > last_sync_with_original_repo_commit_id
      - name: Remove everything under .github/ because I don't need it
        run: rm -rf .github
      - name: Commit and push the change
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Add last_sync_with_original_repo_commit_id
  
  buildandpush:
    needs: [repo-sync]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'Matterbridge' # branch
      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
        #with:
          #image: tonistiigi/binfmt:latest
          #platforms: all
          #platforms: arm/v7
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.6.0
        #with:
          #install: true
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push Matterbridge
        uses: docker/build-push-action@v4.1.0
        with:
          context: .
          file: Dockerfile_whatsappmulti
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            schklom/matterbridge:latest
