name: test commit
on:
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'Feedropolis' # branch
      - run: |
          echo $(git log)
      - run: |
          echo $(git log -n 8)
      - run: |
          echo $(git log --full-history)
      - run: |
          echo $(git log -p -3)
