name: testcommits

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'TTRSS-docker'
      - name: test-commit
        run: |
          git rev-parse refs/heads/TTRSS-docker
          cat $(git ls-remote https://git.tt-rss.org/fox/ttrss-docker-compose HEAD | awk '{ print $1 }') > REMOTE
        
      - name: if yes
        #if: ${{ $REMOTE = $LOCAL }}
        run: |
          echo "OUIIIIIIIIIIIIIII"
          cat REMOTE
        #env:
          #REMOTE: $(git ls-remote https://git.tt-rss.org/fox/ttrss-docker-compose HEAD | awk '{ print $1 }')
          #LOCAL: $(git ls-remote https://github.com/schklom/Mirror-workflows.git refs/heads/TTRSS-docker | awk '{ print $1 }')
      - name: if no
        #if: ${{ $REMOTE = $LOCAL }}
        run: echo "NOOOOOOOOOOOOOON"
