name: test commit
on:
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'Feedropolis' # branch
      - run: |
          git log
      - run: |
          git log -n 2
      - run: |
          git log --full-history
