name: testcommits

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    outputs:
      LOCAL: ${{ steps.commits.outputs.SETLOCAL }}
      REMOTE: ${{ steps.commits.outputs.SETREMOTE }} 
    steps:
      # https://github.com/actions/starter-workflows/issues/68#issuecomment-626239810
      #echo "::set-output name=LOCAL::$(git rev-parse refs/heads/TTRSS-docker)"
      #echo "::set-output name=LOCAL::$(git ls-remote https://github.com/schklom/Mirror-workflows.git refs/heads/TTRSS-docker | awk '{ print $1 }')"
      #echo "::set-output name=REMOTE::$(git ls-remote https://git.tt-rss.org/fox/ttrss-docker-compose HEAD | awk '{ print $1 }')"
      - name: set commits as environment variables
        id: commits
        # https://github.community/t/how-can-i-set-an-expression-as-an-environment-variable-at-workflow-level/16516/9
          #echo "LOCAL=$(git ls-remote https://github.com/schklom/Mirror-workflows.git refs/heads/TTRSS-docker | awk '{ print $1 }')" >> $GITHUB_ENV
          #echo "REMOTE=$(git ls-remote https://git.tt-rss.org/fox/ttrss-docker-compose HEAD | awk '{ print $1 }')" >> $GITHUB_ENV
          
        # https://lannonbr.com/blog/2020-04-16-gh-actions-job-outputs
        run: |
          echo "::set-output name=SETREMOTE::$(git ls-remote https://git.tt-rss.org/fox/ttrss-docker-compose HEAD | awk '{ print $1 }')"
          echo "::set-output name=SETLOCAL::$(git ls-remote https://github.com/schklom/Mirror-workflows.git refs/heads/TTRSS-docker | awk '{ print $1 }')"
      #- name: if no
        #if: env.LOCAL != env.REMOTE
  sync:
    needs: [get_commits]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.get_commits.outputs.LOCAL }}
      - run: echo env.AAA
        env:
          AAA: ${{ needs.get_commits.outputs.LOCAL }}
      - run: echo $AAA
        env:
          AAA: ${{ needs.get_commits.outputs.LOCAL }}
