name: test commit
on:
  workflow_dispatch:

jobs:
  get_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'Feedropolis' # branch
      - run: |
          echo $(git log -n 2)
      - run: |
          echo $(git log -n 4)
      - run: |
          echo $(git log -n 6)
      - run: |
          echo $(git log -n 8)
